#!/bin/bash

##### Interface Customization #####
# only show current working directory
export PS1="%1d > "

# draw lines in front of prompt
setopt promptsubst
export PS1=$'${(r:$COLUMNS::\u2500:)}'$PS1

#############################################################
##################### Personal Aliases ######################
#############################################################
# the command `alias` will show all aliases in this profile incase you want a quick reference
alias ll="ls -FGlAhp"
alias mkdir="mkdir -pv"
alias c="clear"
alias f="open -a Finder ./"
alias ..="cd ../"
alias .2="cd ../.."
alias .3="cd ../../../"

# Requires ncdu to be installed
# built in terminal app for checking folder and file sizes
alias scan="ncdu --color dark -rr -x --exclude .git --exclude node_modules"

# Requires tldr to be installed
alias help="tldr"

# usage: find-file "package.json" -print
alias find-file="find . -path \"**/node_modules\" -prune -o -name"

# pass --dry-run to test before doing
alias sync="rsync -t --verbose --update --human-readable --progress --itemize-changes"
alias minify="perl -pi -e 's/\s+//g'"

# short for perl-in-line
alias pil="perl -pi -e"
alias alert="afplay ~/.alert.wav"
alias mkdirnow="mkdir $(date '+%Y-%m-%d')"

# Requires ffmpeg to be installed
# Usage: video2gif -i in.mov out.gif
alias video2gif='ffmpeg -filter_complex "[0:v] fps=12,scale=700:-1,split [a][b];[a] palettegen [p];[b][p] paletteuse" -i input.mov output.gif'

# Requires ffmpeg to be installed
# Video compression only works in the current directory for files named input.mov
# Usage: vcompress
alias vcompress="ffmpeg -i input.mov -vcodec libx265 -crf 28 output.mp4"

# -r: recursively
# -n: each output line is preceded by its relative line number in the file
alias packages-grep="grep -nr --exclude-dir=node_modules --include package.json"
alias vue-grep="grep -nr --exclude-dir=node_modules --include \*.vue"

# get a time stamp of the current time
alias now="date +%Y-%m-%d-%H-%M-%S"
alias year="date +%Y"
alias month="date +%m"
alias day="date +%d"

# https://www.npmjs.com/package/gnomon
# pipe a command through gnomon to see the run time
alias gtime="gnomon --type=elapsed-total"

# alert the user that a task has finished (get back to work)
# Usage: npm install && gbtw
alias gbtw="say 'get back to work'"

# Usage: find-files "*.vue" -print
alias find-files="find . -path ./node_modules -prune -o -name"

#############################################################
##################### Node/NPM Aliases ######################
#############################################################

# Switch to the right version of node and install packages
alias install="nvm use && npm install"

# build the npm packages, pack it and open in finder so you can move the
# resulting zip around your computer through the GUI
alias pack="npm run build && npm pack && open -a Finder ./"

alias list-npm-local-links="npm ls -g --depth=0 --link=true"
alias count-npm-packages="npm ls --parseable | wc -l"

# build the package and create a local link of the package to be tested in other
# packages or projects. Make sure both projects are using the same version of node.
alias link-local="npm run build && npm link"

## NPM commands ##
# global packages to install
# * npm-check-updates
# * npm-packlist -> then use `npx npm-packlist`
# * gnomon

# npm repo - open project in browser
# npm pack - create NPM module

##### Helful scripts #####
# `find . -path ./node_modules -prune -o -name "*.vue" -print | wc -l` - Get a count of all vue files
# `find . -path ./node_modules -prune -o -name "*.stories.js" -print | xargs code` - Open all stories in a project
# `lsof -P -i TCP -s TCP:LISTEN` - See all active ports
# `npx depcheck` - See unused npm packages for a project
# `npx webpack --profile --json > file.json` - Profile a page

#############################################################
######################## Git Aliases ########################
#############################################################

alias gch="git checkout"
alias gs="git status"
alias grc="git rebase --continue"

# add everything and commit it
alias gac="git add . && git commit"

# fetch all branches on origin and also delete any local branches that are no
# longer on origin
alias fetch="git fetch --prune"

# add eveything and save it as a "work in progress" commit
alias wip="git add . && git commit -m 'chore: work in progress'"

# copy the url of the source repository
alias copy-remote="git remote get-url origin | pbcopy"

# pull the master branch while on a different branch
alias pull-master="git fetch origin master:master"

# pull the main branch while on a different branch
alias pull-main="git fetch origin main:main"

# open the associated PR for the branch you are currently on in GitHub
alias ghpr="gh pr view -w"

# All pull requests on GitHub that are open and you are requested to be a reviewer,
# excluding pull requests that are dependencies (add --web to open in browser)
alias gh-review-requested="gh search prs --state=open --review-requested=@me -- -label:dependencies"

# All pull requests on GitHub that are open and assigned to you
# (add --web to open in browser)
alias gh-my-prs="gh search prs --state=open --assignee=@me"

# All closed pull requests assigned to you (add --web to open in browser)
alias gh-my-closed-prs="gh search prs --assignee=@me --merged"

##### Helful scripts #####
# `git checkout <commit> -- <file_path>` to reset one file to where it was at one point in history
# `git remote set-url origin <remote_url>` to update the remote for a project
# `git commit --author "ESLint <EMAIL>" -m "style: lint project"`
# `git branch -va`: See branches on origin

############## History Analysis and Discovery ###############

# https://www.npmjs.com/package/git-file-history
# needs to be installed globally first (eg. history)
alias history="git-file-history"

# get the name of the current branch
alias branch-name="git rev-parse --abbrev-ref HEAD"

# shows a history of linechanges (eg. git-linechange ./filename.txt)
alias git-linechange="git log --stat --decorate --graph --oneline"

# will show only the commits that changed the file supplied as an argument
# (eg. git-follow ./filename.txt)
alias git-follow="git log --follow -- "

# see a pretty graph of branches in your terminal (eg. graph)
alias graph="git log --graph --decorate --oneline --all"

# See the files changed between now and a branch (usually master)
# git diff --name-only <branch>

## rebasing tools ##
# short for "Git Rebase autoSquash"
# rebase using the best options including an interactive session and
# autosquash of fixup commits (eg. grs master)
alias grs="git rebase --interactive --autosquash"

# commit your changes to be easily merged in with a certain commit
# if you need to fixup the most recent commit, just use `git commit --amend` :)
# (eg. gf <git-sha>)
alias gf="git commit --fixup"

# Quick amend the last commit. Add some code in without changing the commit message
alias amend="git commit --amend --no-edit"

# Use --reset-author flag during rebase to reset all commits to be authored by
# you and reset time stamp to the time in which the rebase occured

#################### Branch Management ######################

# disconnect your branch from origin
alias git-unset="git branch --unset-upstream"

# push the current branch to origin when the branch does not yet exist on origin
# Short for git-push-set-upstream
# get the branch name and then use xargs to take the previous output and add
# that as the argument to git push
alias gpsu="git branch --show-current | xargs git push --set-upstream origin"

###################### Github Tools #########################

# Requires installation of github CLI (gh)
# https://cli.github.com/
alias pr="gh pr view --web"

#############################################################
########################### Other ###########################
#############################################################

## Homebrew
export PATH="/usr/local/sbin:$PATH"

# This is part of the pywal installation

# add python library to the path
export PATH="${PATH}:${HOME}/Library/Python/3.9/bin"
# Import colorscheme from 'wal' asynchronously
# &   # Run the process in the background.
# ( ) # Hide shell job control messages.
(cat ~/.cache/wal/sequences | tr -d "\n" &)
