#!/bin/bash

code --install-extension aeschli.vscode-css-formatter
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bradlc.vscode-tailwindcss
code --install-extension chintans98.markdown-jira
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension ishiyama.vue-autoimport
code --install-extension jock.svg
code --install-extension lokalise.i18n-ally
code --install-extension mohd-akram.vscode-html-format
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.atom-keybindings
code --install-extension octref.vetur
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension silvenon.mdx
code --install-extension sleistner.vscode-fileutils
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-dutch
code --install-extension Tobermory.es6-string-html
code --install-extension Vue.volar
code --install-extension vunguyentuan.vscode-postcss
code --install-extension wix.vscode-import-cost
code --install-extension Yummygum.city-lights-icon-vsc
code --install-extension yummygum.city-lights-theme
code --install-extension yzhang.markdown-all-in-one
